name: Build & Deploy to Firebase
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.2
      - name: Cache Node Modules
        id: node-modules-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      - name: Install Dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FRAMEHUB_F9CFB }}'
          channelId: live
          projectId: framehub-f9cfb
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels