name: Build & Deploy Preview to Firebase
on: pull_request
jobs:
  build_and_preview:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.0.0
          run_install: true
      - name: Build
        run: pnpm run build
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FRAMEHUB_F9CFB }}'
          projectId: framehub-f9cfb
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels