name: Pull Request Checks
on: pull_request
jobs:
  checks:
    name: Pull Request Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.2
      - name: Cache Node Modules
        id: node-modules-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-production-${{ hashFiles('package-lock.json') }}
      - name: Install Dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: npm install
      - name: ESLint
        run: eslint src update_items.js
      - name: stylelint
        run: stylelint "**/*.{css,scss,sass}"
      - name: Update Items
        run: node update_items.js
      - name: Build
        run: npm run build