name: Update & Upload items.json to Firebase
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"
jobs:
  update_and_upload:
    if: (github.event_name != 'push' || !contains(github.event.head_commit.message, 'dependabot')) && !contains(github.event.head_commit.message, 'ci skip')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
      - name: Cache Node Modules
        id: node-modules-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
      - name: Install Dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: npm install -D
      - name: Update items.json
        id: update_items
        run: node update_items.js
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_ADMIN_IDS: ${{ secrets.DISCORD_ADMIN_IDS }}
      - name: Upload items.json to Firebase
        uses: google-github-actions/upload-cloud-storage@main
        if: steps.update_items.outputs.updated == 'true'
        with:
          credentials: ${{ secrets.GCP_CREDENTIALS }}
          path: items.json
          destination: framehub-f9cfb.appspot.com
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: items.json
          path: items.json
